apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-request-deployment
  labels:
    app: ms-request-deployment
spec:
  selector:
    matchLabels:
      app: ms-request-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-request-deployment
    spec:
      containers:
        - name: ms-request
          image: reii23/ms-request
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REQUEST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REQUEST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REQUEST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
